name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: aevea/release-notary
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: aevea/cache
          strip_tag_prefix: v

      - name: Deprecated Outillage builder
        uses: aevea/action-kaniko@master
        with:
          image: outillage/release-notary
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: outillage/cache
          strip_tag_prefix: v
