name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  go:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.15.x]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/magefile/mage
          mage setuptest
          mage test
          mage gomodtidy
